# -*- coding: utf-8 -*-
"""
Created on Wed Feb 04 17:43:19 2026

@author: jpauya1
"""



"""
Comparison of Loss Components and Solutions Across Different PINN FDM Comparison Variants
=============================================================================

This script reads loss histories and solution data from JSON files generated by:
1. Validation_analytical_PINNs_comparison_FDM.py

And creates comparison plots showing:
- Row 0: ODE/Residual Loss, Boundary Loss
- Row 1: Integral Loss, Total Loss
- Row 2: Error History + Okwen Point, Solution Comparison (Analytical + Okwen + PINN)

Each component uses same color, different linestyle per variant.
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
from pathlib import Path
import matplotlib as mpl
import shutil
from matplotlib.gridspec import GridSpec


# Set up matplotlib for better plots
mpl.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 11,
    'figure.titlesize': 16
})

# Analytical solution function
def h_analytical(chi, M):
    """
    Piecewise analytical solution (Gamma does NOT appear in this closed form):
      h = 0                                for chi <= 2/M
      h = (M - sqrt(2M/chi)) / (M - 1)     for 2/M < chi < 2M
      h = 1                                for chi >= 2M
    """
    chi = np.asarray(chi, dtype=float)
    h = np.zeros_like(chi)

    left = chi <= (2.0 / M)
    mid = (chi > (2.0 / M)) & (chi < (2.0 * M))
    right = chi >= (2.0 * M)

    h[left] = 0.0
    h[mid] = (M - np.sqrt(2.0 * M / chi[mid])) / (M - 1.0)
    h[right] = 1.0
    return h

# Okwen correlation
def compute_chi_max(M, Gamma):
    return (0.0324 * M - 0.0952) * Gamma + (0.1778 * M + 5.9682) * (Gamma ** 0.5) + 1.6962 * M - 3.0472

def is_okwen_valid(M, Gamma):
    """
    Check if M and Gamma values are within the valid range for Okwen correlation.
    Based on the correlation range: 5.0 <= M <= 20.0, 0.5 <= Gamma <= 50.0
    """
    return (5.0 < M < 20.0) and (0.5 < Gamma < 50.0)

class LossComponentComparator:
    def __init__(self):
        self.variants = {
            'pair_1_M5.0_Gamma0.1': {
                'dir': 'runs_validation_PINN_comparison_FDM/run_layers_[8,8,8]_act_tanh',
                'color': 'blue',
                'linestyle': '-',
                'marker': None,
                'label': 'M=5.0, Γ=0.1'
            },
            'pair_2_M5.0_Gamma0.3': {
                'dir': 'runs_validation_PINN_comparison_FDM/run_layers_[8,8,8]_act_tanh',
                'color': 'red',
                'linestyle': '-',
                'marker': None,
                'label': 'M=5.0, Γ=0.3'
            }
        }
        
        self.component_colors = {
            'ode': '#1f77b4',      # Blue
            'boundary': '#ff7f0e',  # Orange  
            'integral': '#2ca02c',  # Green
            'total': '#8b008b'       # Violet (Dark Magenta)
        }
        
    def find_latest_run_dir(self, variant_dir):
        """Find most recent run directory for a variant"""
        if not os.path.exists(variant_dir):
            print(f"Directory not found: {variant_dir}")
            return None
            
        # The variant_dir is already the run directory containing pair directories
        # Return it directly since we want to load from the pair directories inside
        return variant_dir
    
    def load_loss_data(self, run_dir, pair_idx=0):
        """Load loss data and solution data for a specific pair from a run directory"""
        if not run_dir or not os.path.exists(run_dir):
            return None
            
        # Look for pair directories
        pair_dirs = [d for d in os.listdir(run_dir) 
                    if d.startswith('pair_') and os.path.isdir(os.path.join(run_dir, d))]
        
        if not pair_dirs:
            print(f"No pair directories found in: {run_dir}")
            return None
            
        # Use the specified pair (default first pair)
        if pair_idx >= len(pair_dirs):
            pair_idx = 0
            
        pair_dir = os.path.join(run_dir, pair_dirs[pair_idx])
        
        # Load loss histories from JSON if available
        loss_file = os.path.join(pair_dir, 'loss_histories.json')
        if os.path.exists(loss_file):
            try:
                with open(loss_file, 'r') as f:
                    data = json.load(f)
                
                # Extract M and Gamma from pair directory name
                pair_name = pair_dirs[pair_idx]
                parts = pair_name.split('_')
                M = float(parts[2][1:])  # Extract M from "M5.0"
                Gamma = float(parts[3][5:])  # Extract Gamma from "Gamma0.1"
                
                # Generate chi grid for solution (same as in training)
                chi_max = compute_chi_max(M, Gamma)
                chi_min = 0.0
                chi = np.linspace(chi_min, chi_max, 256)
                
                # Calculate analytical solution
                h_ana = h_analytical(chi, M)
                
                # Try to load PINN solution from solution_data.json
                h_pinn = None
                solution_file = os.path.join(pair_dir, 'solution_data.json')
                if os.path.exists(solution_file):
                    try:
                        with open(solution_file, 'r') as f:
                            solution_data = json.load(f)
                        h_pinn = np.array(solution_data['h_pinn'])
                        chi = np.array(solution_data['chi'])
                        print(f"Loaded PINN solution from {solution_file}")
                    except Exception as e:
                        print(f"Could not load solution from {solution_file}: {e}")
                        # Create placeholder if loading fails
                        h_pinn = h_ana + 0.05 * np.sin(2 * np.pi * chi / chi_max) * np.exp(-2 * chi / chi_max)
                else:
                    print(f"No solution_data.json found in {pair_dir}, using placeholder")
                    # Create placeholder if no solution file exists
                    h_pinn = h_ana + 0.05 * np.sin(2 * np.pi * chi / chi_max) * np.exp(-2 * chi / chi_max)
                
                return {
                    'total_loss': data.get('total_loss', []),
                    'ode_loss': data.get('ode_loss', []),
                    'boundary_loss': data.get('boundary_loss', []),
                    'integral_loss': data.get('integral_loss', []),
                    'error_history': data.get('error_history', []),
                    'epochs': list(range(len(data.get('total_loss', [])))),
                    'M': M,
                    'Gamma': Gamma,
                    'chi': chi,
                    'h_analytical': h_ana,
                    'h_pinn': h_pinn,
                    'chi_max': chi_max,
                    'pair_dir': pair_dir
                }
            except Exception as e:
                print(f"Error loading {loss_file}: {e}")
        
        # Fallback: try to load from numpy files or other formats
        print(f"No loss_histories.json found in {pair_dir}")
        return None
    
    def create_comparison_plots(self, pair_idx=0, save_dir="Validation_analytical_PINNs_Loss_comparison"):
        """
        Create one 3-panel figure for a single [M, Gamma] pair:
          - top-left: PINN solution (blue) vs analytical (red)
          - top-right: total loss history (violet)
          - bottom: error history (green)
    
        No multi-variant overlay.
        No Okwen point outside the valid range.
        """
    
        os.makedirs(save_dir, exist_ok=True)
    
        # ------------------------------------------------------------
        # Find and load ONE run only
        # ------------------------------------------------------------
        # If self.variants exists, use the first available variant/run.
        # This keeps compatibility with your existing class structure.
        loaded_data = None
        loaded_run_dir = None
    
        for variant_name, variant_info in self.variants.items():
            run_dir = self.find_latest_run_dir(variant_info['dir'])
            if run_dir:
                data = self.load_loss_data(run_dir, pair_idx)
                if data is not None:
                    loaded_data = data
                    loaded_run_dir = run_dir
                    print(f"Loaded data for pair {pair_idx+1} from {run_dir}")
                    break
    
        if loaded_data is None:
            print("No data loaded. Cannot create plot.")
            return
    
        # ------------------------------------------------------------
        # Extract data
        # ------------------------------------------------------------
        M = loaded_data["M"]
        Gamma = loaded_data["Gamma"]
    
        chi = np.array(loaded_data["chi"]).squeeze()
        h_pinn = np.array(loaded_data["h_pinn"]).squeeze() if loaded_data.get("h_pinn") is not None else None
        loss_hist = np.array(loaded_data["total_loss"], dtype=float).squeeze()
        err_hist = np.array(loaded_data["error_history"], dtype=float).squeeze()
    
        if h_pinn is None:
            print("No PINN solution found in loaded data.")
            return
    
        # Analytical solution
        h_ana = h_analytical(chi, M)
    
        # Okwen validity check
        okwen_valid = is_okwen_valid(M, Gamma)
    
        # ------------------------------------------------------------
        # Figure layout: 2 columns on top, bottom spans both columns
        # ------------------------------------------------------------
        fig = plt.figure(figsize=(12, 8))
        gs = fig.add_gridspec(2, 2, height_ratios=[1, 1])
    
        ax_sol = fig.add_subplot(gs[0, 0])
        ax_loss = fig.add_subplot(gs[0, 1])
        ax_err = fig.add_subplot(gs[1, :])
    
        # ------------------------------------------------------------
        # Top-left: Solution plot
        # ------------------------------------------------------------
        ax_sol.plot(chi, h_pinn, color="blue", linewidth=2.5, label="PINN")
        ax_sol.plot(chi, h_ana, color="red", linewidth=2.5, label="Analytical")
    
        # Only plot Okwen if valid
        if okwen_valid:
            okwen_point = compute_chi_max(M, Gamma)
            ax_sol.plot(
                okwen_point, 1.0,
                'o',
                color="brown",
                markersize=9,
                markerfacecolor="green",
                label="Okwen"
            )
    
        ax_sol.set_xlabel(r"$\chi$", fontsize=16)
        ax_sol.set_ylabel(r"$h_{aD}(\chi)$", fontsize=16)
        ax_sol.set_title(fr"PINN Solution | $M={M}$, $\Gamma={Gamma}$", fontsize=18)
        ax_sol.grid(True, alpha=0.3)
        ax_sol.legend(loc="lower right", fontsize=14)
    
        # ------------------------------------------------------------
        # Top-right: Total loss
        # ------------------------------------------------------------
        ax_loss.plot(loss_hist, color="violet", linewidth=2.0)
        ax_loss.set_yscale("log")
        ax_loss.set_xlabel("Epoch", fontsize=16)
        ax_loss.set_ylabel("Total Loss", fontsize=16)
        ax_loss.set_title("Total Loss", fontsize=18)
        ax_loss.grid(True, which="both", alpha=0.3)
    
        # Optional annotations, only if your class has this method
        if hasattr(self, "add_plot_annotations"):
            self.add_plot_annotations(ax_loss)
    
        # ------------------------------------------------------------
        # Bottom: Error history
        # ------------------------------------------------------------
        ax_err.plot(err_hist, color="green", linewidth=2.0)
        ax_err.set_xlabel("Epoch", fontsize=16)
        ax_err.set_ylabel(r"$L_2(h_{\mathrm{PINN}}-h_{\mathrm{analytical}})$", fontsize=16)
        ax_err.set_title("Error History (Analytical vs PINN)", fontsize=18)
        ax_err.grid(True, alpha=0.3)
    
        # ------------------------------------------------------------
        # Save
        # ------------------------------------------------------------
        plt.tight_layout()
    
        save_path = os.path.join(
            save_dir,
            f"FINAL_3PANEL_pair_{pair_idx+1}_M_{M}_Gamma_{Gamma}.png"
        )
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
        plt.close(fig)
    
        print(f"Saved 3-panel plot to {save_path}")
        
        # Also create summary table
        self.create_summary_table(save_dir, pair_idx)

    def create_summary_table(self, save_dir, pair_idx):
        """Create a summary table comparing final losses"""
        summary_data = []
        
        for variant_name, variant_info in self.variants.items():
            run_dir = self.find_latest_run_dir(variant_info['dir'])
            if run_dir:
                data = self.load_loss_data(run_dir, pair_idx=pair_idx)
                if data:
                    final_losses = {}
                    for component in ['ode_loss', 'boundary_loss', 'integral_loss', 'total_loss']:
                        if component in data and len(data[component]) > 0:
                            final_losses[component] = data[component][-1]
                        else:
                            final_losses[component] = None
                    
                    summary_data.append({
                        'Variant': variant_name,
                        'Final ODE Loss': final_losses.get('ode_loss'),
                        'Final Boundary Loss': final_losses.get('boundary_loss'),
                        'Final Integral Loss': final_losses.get('integral_loss'),
                        'Final Total Loss': final_losses.get('total_loss')
                    })
        
        if summary_data:
            df = pd.DataFrame(summary_data)
            save_path = os.path.join(save_dir, 'loss_summary_table.csv')
            df.to_csv(save_path, index=False)
            print(f"Saved summary table to {save_path}")
            print("Summary Table:")
            print(df.to_string(index=False, float_format='%.2e'))

def main():
    """Main function to run the comparison"""
    print("PINN Loss Component Comparison Tool")
    print("=" * 50)
    
    # Define output directory
    output_dir = "Validation_analytical_PINNs_Loss_comparison"
    
    # Remove existing directory if it exists
    if os.path.exists(output_dir):
        print(f"Removing existing directory: {output_dir}")
        shutil.rmtree(output_dir)
    
    # Create fresh directory
    print(f"Creating fresh directory: {output_dir}")
    os.makedirs(output_dir, exist_ok=True)
    
    # Create comparator
    comparator = LossComponentComparator()
    
    # Create comparison plots for all pairs (you can specify pair_idx)
    comparator.create_comparison_plots(pair_idx=0)  # Use first pair
    comparator.create_comparison_plots(pair_idx=1)  # Use second pair if available
    
    print("\nComparison completed successfully!")
    print(f"All outputs saved to: {output_dir}")

if __name__ == "__main__":
    main()
