# -*- coding: utf-8 -*-
"""
Created on Wed Feb 04 17:43:19 2026

@author: jpauya1
"""



"""
Comparison of Loss Components and Solutions Across Different PINN Variants
=============================================================================

This script reads loss histories and solution data from JSON files generated by:
1. PINNs_Okwen_best_grid_search_transfer_learning_highest_Gamma_M.py (Fixed Weights)

And creates comparison plots showing:
- Row 0: Solution Comparison (Analytical + Okwen + PINN), Error History
- Row 1: ODE/Residual Loss, Boundary Loss
- Row 2: Integral Loss, Total Loss
- Bar Plot: Final Losses Comparison Across All Pairs

Each component uses same color, different linestyle per variant.
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
from pathlib import Path
import matplotlib as mpl
import shutil


# Set up matplotlib for better plots
mpl.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 11,
    'figure.titlesize': 16
})

# Analytical solution function
def h_analytical(chi, M):
    """
    Piecewise analytical solution (Gamma does NOT appear in this closed form):
      h = 0                                for chi <= 2/M
      h = (M - sqrt(2M/chi)) / (M - 1)     for 2/M < chi < 2M
      h = 1                                for chi >= 2M
    """
    chi = np.asarray(chi, dtype=float)
    h = np.zeros_like(chi)

    left = chi <= (2.0 / M)
    mid = (chi > (2.0 / M)) & (chi < (2.0 * M))
    right = chi >= (2.0 * M)

    h[left] = 0.0
    h[mid] = (M - np.sqrt(2.0 * M / chi[mid])) / (M - 1.0)
    h[right] = 1.0
    return h

# Okwen correlation
def compute_chi_max(M, Gamma):
    return (0.0324 * M - 0.0952) * Gamma + (0.1778 * M + 5.9682) * (Gamma ** 0.5) + 1.6962 * M - 3.0472

def is_okwen_valid(M, Gamma):
    """
    Check if M and Gamma values are within the valid range for Okwen correlation.
    Based on the correlation range: 5.0 < M < 20.0, 0.5 < Gamma < 50.0
    """
    return (5.0 < M < 20.0) and (0.5 < Gamma < 50.0)

class LossComponentComparator:
    def __init__(self, transfer_learning_dir="runs_PINN_best_grid_search_transfer_learning_highest_Gamma_M"):
        self.transfer_learning_dir = transfer_learning_dir
        self.variants = {}
        
    def find_run_directories(self):
        if not os.path.exists(self.transfer_learning_dir):
            print(f"Transfer learning directory not found: {self.transfer_learning_dir}")
            return []
        run_dirs = []
        for item in os.listdir(self.transfer_learning_dir):
            run_path = os.path.join(self.transfer_learning_dir, item)
            if os.path.isdir(run_path) and item.startswith("run_layers_"):
                run_dirs.append(run_path)
        return sorted(run_dirs)

    def parse_run_name(self, run_dir):
        # "run_layers_[32,32,32]_act_tanh"
        run_name = os.path.basename(run_dir)
        parts = run_name.split("_")
        layers_start_idx = parts.index("layers") + 1
        layers_end_idx = parts.index("act")
        layers_parts = parts[layers_start_idx:layers_end_idx]
        layers_str = "_".join(layers_parts)  # "[32,32,32]"
        activation = parts[layers_end_idx + 1]
        layers_clean = layers_str.replace("[", "").replace("]", "")
        variant_id = f"[{layers_clean}]_{activation}"
        return variant_id, layers_clean, activation
    
    def load_loss_data(self, run_dir, pair_idx=0):
        if not run_dir or not os.path.exists(run_dir):
            return None

        pair_dirs = [
            d for d in os.listdir(run_dir)
            if d.startswith("pair_") and os.path.isdir(os.path.join(run_dir, d))
        ]
        if not pair_dirs:
            print(f"No pair directories found in: {run_dir}")
            return None

        pair_dirs = sorted(pair_dirs)
        if pair_idx >= len(pair_dirs):
            pair_idx = 0

        pair_dirname = pair_dirs[pair_idx]
        pair_dir = os.path.join(run_dir, pair_dirname)

        loss_file = os.path.join(pair_dir, "loss_histories.json")
        if not os.path.exists(loss_file):
            return None

        try:
            with open(loss_file, "r") as f:
                data = json.load(f)

            # parse M & Gamma from "pair_1_M6.0_Gamma1.0"
            parts = pair_dirname.split("_")
            M = None
            Gamma = None
            for p in parts:
                if p.startswith("M"):
                    M = float(p[1:])
                if p.startswith("Gamma"):
                    Gamma = float(p[5:])
            if M is None or Gamma is None:
                raise ValueError(f"Could not parse M/Gamma from {pair_dirname}")

            # solution data
            h_pinn = None
            chi = None
            solution_file = os.path.join(pair_dir, "solution_data.json")
            if os.path.exists(solution_file):
                try:
                    with open(solution_file, "r") as f:
                        solution_data = json.load(f)
                    h_pinn = np.array(solution_data["h_pinn"], dtype=float)
                    chi = np.array(solution_data["chi"], dtype=float)
                    print(f"Loaded PINN solution from {solution_file}")
                except Exception as e:
                    print(f"Could not load solution from {solution_file}: {e}")

            if chi is None:
                chi_max = compute_chi_max(M, Gamma)
                chi = np.linspace(0.0, chi_max, 256)

            h_ana = h_analytical(chi, M)

            if h_pinn is None:
                chi_max = compute_chi_max(M, Gamma)
                h_pinn = h_ana + 0.05 * np.sin(2 * np.pi * chi / chi_max) * np.exp(-2 * chi / chi_max)

            total_loss = data.get("total_loss", [])
            epochs = list(range(len(total_loss))) if isinstance(total_loss, list) else []

            return {
                "total_loss": data.get("total_loss", []),
                "ode_loss": data.get("ode_loss", []),
                "boundary_loss": data.get("boundary_loss", []),
                "integral_loss": data.get("integral_loss", []),
                "error_history": data.get("error_history", []),
                "epochs": epochs,
                "M": M,
                "Gamma": Gamma,
                "chi": chi,
                "h_analytical": h_ana,
                "h_pinn": h_pinn,
                "chi_max": compute_chi_max(M, Gamma),
                "pair_dir": pair_dir,
            }

        except Exception as e:
            print(f"Error loading {loss_file}: {e}")
            return None

    def load_all_variants(self, pair_idx=0):
        run_dirs = self.find_run_directories()
        for run_dir in run_dirs:
            variant_id, layers_str, activation = self.parse_run_name(run_dir)
            data = self.load_loss_data(run_dir, pair_idx)
            if data:
                self.variants[variant_id] = {
                    "data": data,
                    "style": {
                        "color": "black",  # Default color since no grid search
                        "linestyle": "-",    # Solid line
                        "label": f"[{layers_str}] | {activation}",
                    },
                    "layers": layers_str,
                    "activation": activation,
                    "run_dir": run_dir,
                }
                print(f"Loaded data for {variant_id}")
            else:
                print(f"Failed to load data for {variant_id}")

    def create_comparison_plots(self, save_dir="PINNs_Okwen_best_grid_search_transfer_learning_highest_Gamma_M_Loss_comparison"):
        """Create 3x2 comparison plots with all pairs together for comparison"""
        
        # Create save directory only if it doesn't exist
        if not os.path.exists(save_dir):
            os.makedirs(save_dir, exist_ok=True)
        
        # Load all variants for all pairs
        self.variants_all_pairs = {}
        pair_colors = ['purple']  # Colors for pair 1, 2, 3
        pair_labels = ['[M, Γ] = [19.0, 49.0])']
        
        for pair_idx in range(1):
            self.variants = {}
            self.load_all_variants(pair_idx)
            
            if self.variants:
                # Add pair index and color/style to each variant
                for variant_id, variant_info in self.variants.items():
                    variant_info['pair_idx'] = pair_idx
                    variant_info['pair_color'] = pair_colors[pair_idx]
                    variant_info['pair_label'] = pair_labels[pair_idx]
                    # Update style to use pair color and remove variant prefix from label
                    variant_info['style']['color'] = pair_colors[pair_idx]
                    variant_info['style']['label'] = pair_labels[pair_idx]
                
                self.variants_all_pairs[pair_idx] = dict(self.variants)
            else:
                print(f"No data loaded for pair {pair_idx}")

        if not self.variants_all_pairs:
            print("No data loaded for any pairs")
            return

        # Create combined plots
        self.create_combined_bar_plot_layout(save_dir)
        self.create_combined_line_plot_layout(save_dir)
        self.create_combined_summary_table(save_dir)

    def _sorted_variant_items(self):
        """Stable ordering: by layers then activation (gelu, swish, tanh) if present."""
        activation_order = ["gelu", "swish", "tanh"]

        def layers_key(layers_str):
            try:
                return tuple(int(x.strip()) for x in layers_str.split(","))
            except Exception:
                return (9999,)

        def activation_key(act):
            return activation_order.index(act) if act in activation_order else 999

        items = list(self.variants.items())
        items.sort(key=lambda kv: (layers_key(kv[1].get("layers", "")), activation_key(kv[1].get("activation", ""))))
        return items

    # ----------------------------- #
    # COMBINED BAR plot layout
    # ----------------------------- #
    def create_combined_bar_plot_layout(self, save_dir):
        """Create 3x2 bar plot layout with all pairs compared together"""
        import matplotlib.patches as mpatches

        # Collect all variants from all pairs
        all_variants = []
        for pair_idx, variants in self.variants_all_pairs.items():
            for variant_id, variant_info in variants.items():
                all_variants.append((pair_idx, variant_id, variant_info))
        
        # Check if any pair has Gamma >= 0.5 (no analytical solution)
        has_high_gamma = any(variant_info["data"]["Gamma"] >= 0.5 for _, _, variant_info in all_variants)
        
        import matplotlib.gridspec as gridspec

        fig = plt.figure(figsize=(16, 12))
        
        if has_high_gamma:
            # For Gamma >= 0.5: Solution Comparison occupies entire first row
            gs = gridspec.GridSpec(3, 2, figure=fig, hspace=0.3, wspace=0.3)
            ax_sol = fig.add_subplot(gs[0, :])  # First row, all columns
            
            # Remaining subplots
            ax_ode = fig.add_subplot(gs[1, 0])
            ax_boundary = fig.add_subplot(gs[1, 1])
            ax_integral = fig.add_subplot(gs[2, 0])
            ax_total = fig.add_subplot(gs[2, 1])
            
            # Reorganize axes for loss components
            axes = [[ax_sol, None], [ax_ode, ax_boundary], [ax_integral, ax_total]]
        else:
            # For Gamma < 0.5: Normal 3x2 layout
            axes = fig.subplots(3, 2)
        
        # Create legend for pairs
        pair_colors = ['purple']
        pair_labels = ['[M, Γ] = [19.0, 49.0])']
        legend_handles = [mpatches.Patch(color=pair_colors[i], label=pair_labels[i]) for i in range(1)]
        
        if has_high_gamma:
            # For Gamma >= 0.5: Solution Comparison occupies entire first row
            ax_sol = axes[0][0]  # Already created with gridspec spanning full width
            
            # Plot PINN solutions for all pairs
            for pair_idx, _, variant_info in all_variants:
                data = variant_info["data"]
                style = variant_info["style"]
                h_pinn = data.get("h_pinn", None)
                if h_pinn is not None:
                    ax_sol.plot(data["chi"], h_pinn, color=style["color"], linestyle=style["linestyle"], 
                              linewidth=2.0, label=style["label"], alpha=0.8)
            
            # Okwen point for each pair (also in high-gamma branch)
            for pair_idx, _, variant_info in all_variants:
                data = variant_info["data"]
                M = data["M"]
                Gamma = data["Gamma"]
                if is_okwen_valid(M, Gamma):
                    chi_ok = compute_chi_max(M, Gamma)
                    ax_sol.scatter(
                        chi_ok, 1.0,
                        s=80, marker='o',
                        facecolor='yellow', edgecolor='black',
                        zorder=6,
                        label=None  # avoid repeated legend labels
                    )
                    ax_sol.annotate(
                        f"Okwen",
                        (chi_ok, 1.0),
                        textcoords="offset points", xytext=(0, -17),
                        ha='center', fontsize=8
                    )
            
            ax_sol.set_xlabel("χ", fontsize=11)
            ax_sol.set_ylabel("h(χ)", fontsize=11)
            ax_sol.set_title("PINN Solution", fontsize=13, fontweight='bold')
            ax_sol.grid(True, alpha=0.3)
            ax_sol.set_ylim([-0.1, 1.1])
            
            # Add single legend handle for Okwen
            from matplotlib.lines import Line2D
            okwen_handle = Line2D([0], [0], marker='o', linestyle='None',
                                  markerfacecolor='yellow', markeredgecolor='black',
                                  markersize=8, label='Okwen χ_max')
            handles, labels = ax_sol.get_legend_handles_labels()
            ax_sol.legend(handles + [okwen_handle], labels + ['Okwen χ_max'], loc='best', fontsize=8)
            
            # Adjust remaining subplots (shifted up)
            loss_components = [
                ('ode_loss', 'Residual Loss', axes[1][0]),
                ('boundary_loss', 'Boundary Loss', axes[1][1]),
                ('integral_loss', 'Integral Loss', axes[2][0]),
                ('total_loss', 'Total Loss', axes[2][1])
            ]
            
        else:
            # For Gamma < 0.5: Normal layout with analytical solution
            # First row: [0,0] = Solution Comparison, [0,1] = Error History
            # Solution comparison at [0,0] - show all pairs
            ax_sol = axes[0][0]
            
            # Plot analytical solution once
            if all_variants:
                first_data = all_variants[0][2]["data"]
                M = first_data["M"]
                chi = first_data["chi"]
                ax_sol.plot(chi, h_analytical(chi, M), "k-", linewidth=2.5, label="Analytical", alpha=0.8)
                
                # Okwen point for each pair
                for pair_idx, _, variant_info in all_variants:
                    if pair_idx == 0:  # Only show once for first pair (same M)
                        data = variant_info["data"]
                        Gamma = data["Gamma"]
                        chi_max_okwen = compute_chi_max(M, Gamma)
                        if is_okwen_valid(M, Gamma):
                            ax_sol.plot(chi_max_okwen, 1.0, "o", color="gray", markersize=8, markerfacecolor="gray", 
                                      markeredgecolor="black", label="Okwen χ_max")
                
                # Plot PINN solutions for all pairs
                for pair_idx, _, variant_info in all_variants:
                    data = variant_info["data"]
                    style = variant_info["style"]
                    h_pinn = data.get("h_pinn", None)
                    if h_pinn is not None:
                        ax_sol.plot(chi, h_pinn, color=style["color"], linestyle=style["linestyle"], 
                                  linewidth=2.0, label=style["label"], alpha=0.8)
            
            ax_sol.set_xlabel("χ", fontsize=11)
            ax_sol.set_ylabel("h(χ)", fontsize=11)
            ax_sol.set_title(f"Solution Comparison (M={first_data['M']}, All Γ values)", fontsize=13, fontweight='bold')
            ax_sol.grid(True, alpha=0.3)
            ax_sol.legend(loc='best', fontsize=8)
            ax_sol.set_ylim([-0.1, 1.1])
            
            # Error history at [0,1] - show all pairs
            ax_err = axes[0][1]
            for pair_idx, _, variant_info in all_variants:
                data = variant_info["data"]
                style = variant_info["style"]
                error_history = data.get("error_history", [])
                if error_history:
                    epochs = data["epochs"]
                    ax_err.plot(epochs, error_history, color=style["color"], linestyle=style["linestyle"],
                              linewidth=2.0, label=style["label"], alpha=0.8)
            
            ax_err.set_yscale('log')
            ax_err.set_xlabel('Epoch', fontsize=11)
            ax_err.set_ylabel(r"$L_2(h_{\mathrm{PINN}}-h_{\mathrm{analytical}})$", fontsize=11)
            ax_err.set_title('Error History (All Pairs)', fontsize=13, fontweight='bold')
            ax_err.grid(True, which="both", alpha=0.3)
            ax_err.legend(loc='best', fontsize=9)
            
            # Remaining 4 subplots for loss components
            loss_components = [
                ('ode_loss', 'Residual Loss', axes[1][0]),
                ('boundary_loss', 'Boundary Loss', axes[1][1]),
                ('integral_loss', 'Integral Loss', axes[2][0]),
                ('total_loss', 'Total Loss', axes[2][1])
            ]
        
        # Plot loss components (same for both cases)
        for component, title, ax in loss_components:
            final_values, labels, colors = [], [], []
            for pair_idx, _, variant_info in all_variants:
                data = variant_info["data"]
                style = variant_info["style"]
                losses = data.get(component, [])
                if losses:
                    final_values.append(losses[-1])
                    labels.append(style["label"])
                    colors.append(style["color"])
            
            if final_values:
                x = np.arange(len(final_values))
                ax.bar(x, final_values, color=colors, alpha=0.9)
                ax.set_yscale('log')
                ax.set_title(title, fontsize=13, fontweight='bold')
                ax.set_xlabel('')
                ax.set_ylabel('Final Loss', fontsize=11)
                ax.set_xticks(x)
                # Use cleaner labeling without rotation
                ax.set_xticklabels(labels, fontsize=8, ha='center')
                ax.grid(True, which='both', alpha=0.3)
                # Adjust layout to prevent label cutoff
                plt.tight_layout()
        
        plt.tight_layout()
        save_path = os.path.join(save_dir, 'bar_comparison_all_pairs_combined.png')
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved combined bar plot to {save_path}")

    # ----------------------------- #
    # COMBINED LINE plot layout
    # ----------------------------- #
    def create_combined_line_plot_layout(self, save_dir):
        """Create 3x2 line plot layout with all pairs compared together"""
        import matplotlib.patches as mpatches

        # Collect all variants from all pairs
        all_variants = []
        for pair_idx, variants in self.variants_all_pairs.items():
            for variant_id, variant_info in variants.items():
                all_variants.append((pair_idx, variant_id, variant_info))
        
        # Check if any pair has Gamma >= 0.5 (no analytical solution)
        has_high_gamma = any(variant_info["data"]["Gamma"] >= 0.5 for _, _, variant_info in all_variants)
        
        import matplotlib.gridspec as gridspec

        fig = plt.figure(figsize=(16, 18))
        
        if has_high_gamma:
            # For Gamma >= 0.5: Solution Comparison occupies entire first row
            gs = gridspec.GridSpec(3, 2, figure=fig, hspace=0.3, wspace=0.3)
            ax_sol = fig.add_subplot(gs[0, :])  # First row, all columns
            
            # Remaining subplots
            ax_ode = fig.add_subplot(gs[1, 0])
            ax_boundary = fig.add_subplot(gs[1, 1])
            ax_integral = fig.add_subplot(gs[2, 0])
            ax_total = fig.add_subplot(gs[2, 1])
            
            # Reorganize axes for loss components
            axes = [[ax_sol, None], [ax_ode, ax_boundary], [ax_integral, ax_total]]
        else:
            # For Gamma < 0.5: Normal 3x2 layout
            axes = fig.subplots(3, 2)
        
        # Create legend for pairs
        pair_colors = ['blue', 'red', 'green']
        pair_labels = ['[M, Γ] = [6.0, 1.0])', '[M, Γ] = [6.0, 17.0]', '[M, Γ] = [6.0, 33.0]']
        legend_handles = [mpatches.Patch(color=pair_colors[i], label=pair_labels[i]) for i in range(3)]
        
        if has_high_gamma:
            # For Gamma >= 0.5: Solution Comparison occupies entire first row
            ax_sol = axes[0][0]  # Already created with gridspec spanning full width
            
            # Plot PINN solutions for all pairs
            for pair_idx, _, variant_info in all_variants:
                data = variant_info["data"]
                style = variant_info["style"]
                h_pinn = data.get("h_pinn", None)
                if h_pinn is not None:
                    ax_sol.plot(data["chi"], h_pinn, color=style["color"], linestyle=style["linestyle"], 
                              linewidth=2.0, label=style["label"], alpha=0.8)
            
            # Okwen point for each pair (also in high-gamma branch)
            for pair_idx, _, variant_info in all_variants:
                data = variant_info["data"]
                M = data["M"]
                Gamma = data["Gamma"]
                if is_okwen_valid(M, Gamma):
                    chi_ok = compute_chi_max(M, Gamma)
                    ax_sol.scatter(
                        chi_ok, 1.0,
                        s=80, marker='o',
                        facecolor='yellow', edgecolor='black',
                        zorder=6,
                        label=None  # avoid repeated legend labels
                    )
                    ax_sol.annotate(
                        f"Okwen",
                        (chi_ok, 1.0),
                        textcoords="offset points", xytext=(0, 10),
                        ha='center', fontsize=8
                    )
            
            ax_sol.set_xlabel("χ", fontsize=11)
            ax_sol.set_ylabel("h(χ)", fontsize=11)
            ax_sol.set_title("PINN Solution", fontsize=13, fontweight='bold')
            ax_sol.grid(True, alpha=0.3)
            ax_sol.set_ylim([-0.1, 1.1])
            
            # Add single legend handle for Okwen
            from matplotlib.lines import Line2D
            okwen_handle = Line2D([0], [0], marker='o', linestyle='None',
                                  markerfacecolor='yellow', markeredgecolor='black',
                                  markersize=8, label='Okwen χ_max')
            handles, labels = ax_sol.get_legend_handles_labels()
            ax_sol.legend(handles + [okwen_handle], labels + ['Okwen χ_max'], loc='best', fontsize=8)
            
            # Adjust remaining subplots (shifted up)
            loss_components = [
                ('ode_loss', 'Residual Loss', axes[1][0]),
                ('boundary_loss', 'Boundary Loss', axes[1][1]),
                ('integral_loss', 'Integral Loss', axes[2][0]),
                ('total_loss', 'Total Loss', axes[2][1])
            ]
            
        else:
            # For Gamma < 0.5: Normal layout with analytical solution
            # First row: [0,0] = Solution Comparison, [0,1] = Error History
            # Solution comparison at [0,0] - show all pairs
            ax_sol = axes[0][0]
            
            # Plot analytical solution once
            if all_variants:
                first_data = all_variants[0][2]["data"]
                M = first_data["M"]
                chi = first_data["chi"]
                ax_sol.plot(chi, h_analytical(chi, M), "k-", linewidth=2.5, label="Analytical", alpha=0.8)
                
                # Okwen point for each pair
                for pair_idx, _, variant_info in all_variants:
                    if pair_idx == 0:  # Only show once for first pair (same M)
                        data = variant_info["data"]
                        Gamma = data["Gamma"]
                        chi_max_okwen = compute_chi_max(M, Gamma)
                        if is_okwen_valid(M, Gamma):
                            ax_sol.plot(chi_max_okwen, 1.0, "o", color="gray", markersize=8, markerfacecolor="gray", 
                                      markeredgecolor="black", label="Okwen χ_max")
                
                # Plot PINN solutions for all pairs
                for pair_idx, _, variant_info in all_variants:
                    data = variant_info["data"]
                    style = variant_info["style"]
                    h_pinn = data.get("h_pinn", None)
                    if h_pinn is not None:
                        ax_sol.plot(chi, h_pinn, color=style["color"], linestyle=style["linestyle"], 
                                  linewidth=2.0, label=style["label"], alpha=0.8)
            
            ax_sol.set_xlabel("χ", fontsize=11)
            ax_sol.set_ylabel("h(χ)", fontsize=11)
            ax_sol.set_title(f"Solution Comparison (M={first_data['M']}, All Γ values)", fontsize=13, fontweight='bold')
            ax_sol.grid(True, alpha=0.3)
            ax_sol.legend(loc='best', fontsize=8)
            ax_sol.set_ylim([-0.1, 1.1])
            
            # Error history at [0,1] - show all pairs
            ax_err = axes[0][1]
            for pair_idx, _, variant_info in all_variants:
                data = variant_info["data"]
                style = variant_info["style"]
                error_history = data.get("error_history", [])
                if error_history:
                    epochs = data["epochs"]
                    ax_err.plot(epochs, error_history, color=style["color"], linestyle=style["linestyle"],
                              linewidth=2.0, label=style["label"], alpha=0.8)
            
            ax_err.set_yscale('log')
            ax_err.set_xlabel('Epoch', fontsize=11)
            ax_err.set_ylabel(r"$L_2(h_{\mathrm{PINN}}-h_{\mathrm{analytical}})$", fontsize=11)
            ax_err.set_title('Error History (All Pairs)', fontsize=13, fontweight='bold')
            ax_err.grid(True, which="both", alpha=0.3)
            ax_err.legend(loc='best', fontsize=9)
            
            # Remaining 4 subplots for loss components (line plots)
            loss_components = [
                ('ode_loss', 'Residual Loss', axes[1,0]),
                ('boundary_loss', 'Boundary Loss', axes[1,1]),
                ('integral_loss', 'Integral Loss', axes[2,0]),
                ('total_loss', 'Total Loss', axes[2,1])
            ]
        
        # Plot loss components (same for both cases)
        for component, title, ax in loss_components:
            for pair_idx, _, variant_info in all_variants:
                data = variant_info["data"]
                style = variant_info["style"]
                losses = data.get(component, [])
                if losses:
                    epochs = data["epochs"]
                    ax.plot(epochs, losses, color=style["color"], linestyle=style["linestyle"],
                           linewidth=2.0, label=style["label"], alpha=0.8)
            
            ax.set_yscale('log')
            ax.set_xlabel('Epoch', fontsize=11)
            ax.set_ylabel('Loss', fontsize=11)
            ax.set_title(title, fontsize=13, fontweight='bold')
            ax.grid(True, which="both", alpha=0.3)
            ax.legend(loc='best', fontsize=9)
        
        plt.tight_layout()
        save_path = os.path.join(save_dir, 'line_comparison_all_pairs_combined.png')
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved combined line plot to {save_path}")

    def create_combined_summary_table(self, save_dir):
        """Create a summary table comparing final losses across all pairs"""
        summary_data = []
        
        for pair_idx, variants in self.variants_all_pairs.items():
            for variant_id, variant_info in variants.items():
                data = variant_info["data"]
                final_losses = {}
                for component in ['ode_loss', 'boundary_loss', 'integral_loss', 'total_loss']:
                    losses = data.get(component, [])
                    if losses:
                        final_losses[component] = losses[-1]
                    else:
                        final_losses[component] = None
                
                summary_data.append({
                    'Pair': f"Pair {pair_idx + 1}",
                    'Gamma': data["Gamma"],
                    'Variant': variant_info["style"]["label"].split(' - ')[0],  # Remove pair suffix
                    'Final ODE Loss': final_losses.get('ode_loss'),
                    'Final Boundary Loss': final_losses.get('boundary_loss'),
                    'Final Integral Loss': final_losses.get('integral_loss'),
                    'Final Total Loss': final_losses.get('total_loss')
                })
        
        if summary_data:
            df = pd.DataFrame(summary_data)
            save_path = os.path.join(save_dir, 'loss_summary_table_all_pairs.csv')
            df.to_csv(save_path, index=False)
            print(f"Saved combined summary table to {save_path}")
            print("Combined Summary Table:")
            print(df.to_string(index=False, float_format='%.2e'))

def main():
    """Main function to run the comparison"""
    print("PINN Transfer Learning Loss Component Comparison Tool")
    print("=" * 60)
    
    # Define output directory
    output_dir = "PINNs_Okwen_best_grid_search_transfer_learning_highest_Gamma_M_Loss_comparison"
    
    # Remove existing directory if it exists
    if os.path.exists(output_dir):
        print(f"Removing existing directory: {output_dir}")
        shutil.rmtree(output_dir)
    
    # Create fresh directory
    print(f"Creating fresh directory: {output_dir}")
    os.makedirs(output_dir, exist_ok=True)
    
    # Create comparator
    comparator = LossComponentComparator()
    
    # Create combined comparison plots for all pairs together
    comparator.create_comparison_plots()
    
    print("\nComparison completed successfully!")
    print(f"All outputs saved to: {output_dir}")

if __name__ == "__main__":
    main()
