# -*- coding: utf-8 -*-
"""
Created on Wed Feb 04 17:43:19 2026

@author: jpauya1
"""



"""
Comparison of Loss Components and Solutions Across Different PINN Variants
=============================================================================

This script reads loss histories and solution data from JSON files generated by:
1. Validation_analytical_PINNs_base_case_grid_search.py
2. Validation_analytical_PINNs_adaptive_gradient_based_weighting_loss_best_grid_search.py

And creates comparison plots showing:
- Row 0: Solution Comparison (Analytical + Okwen + PINN), Error History
- Row 1: ODE/Residual Loss, Boundary Loss
- Row 2: Integral Loss, Total Loss
- Bar Plot: Final Losses Comparison Across All Variants

Each component uses same color, different linestyle per variant.
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
from pathlib import Path
import matplotlib as mpl
import shutil


# Set up matplotlib for better plots
mpl.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 11,
    'figure.titlesize': 16
})

# Analytical solution function
def h_analytical(chi, M):
    """
    Piecewise analytical solution (Gamma does NOT appear in this closed form):
      h = 0                                for chi <= 2/M
      h = (M - sqrt(2M/chi)) / (M - 1)     for 2/M < chi < 2M
      h = 1                                for chi >= 2M
    """
    chi = np.asarray(chi, dtype=float)
    h = np.zeros_like(chi)

    left = chi <= (2.0 / M)
    mid = (chi > (2.0 / M)) & (chi < (2.0 * M))
    right = chi >= (2.0 * M)

    h[left] = 0.0
    h[mid] = (M - np.sqrt(2.0 * M / chi[mid])) / (M - 1.0)
    h[right] = 1.0
    return h

# Okwen correlation
def compute_chi_max(M, Gamma):
    return (0.0324 * M - 0.0952) * Gamma + (0.1778 * M + 5.9682) * (Gamma ** 0.5) + 1.6962 * M - 3.0472

class LossComponentComparator:
    def __init__(self):
        self.variants = {
            'Fixed': {
                'dir': 'runs_validation_PINN_base_case_grid_search',
                'color': 'blue',
                'linestyle': '-',
                'marker': None,
                'label': 'Fixed',
                'target_folder': 'run_layers_[32,32,32]_act_tanh'
            },
            'Adaptive': {
                'dir': 'runs_validation_PINN_adaptive_gradient_based_weighting_loss_best_grid_search',
                'color': 'red',
                'linestyle': '-',
                'marker': None,
                'label': 'Adaptive',
                'target_folder': 'run_layers_[32,32,32]_act_tanh'
            }
        }
        
        self.component_colors = {
            'ode': '#1f77b4',      # Blue
            'boundary': '#ff7f0e',  # Orange  
            'integral': '#2ca02c',  # Green
            'total': '#8b008b'       # Violet (Dark Magenta)
        }
        
    def find_latest_run_dir(self, variant_dir):
        """Find specific target folder for a variant"""
        if not os.path.exists(variant_dir):
            print(f"Directory not found: {variant_dir}")
            return None
            
        # Get the variant info to find target folder
        variant_name = None
        for name, info in self.variants.items():
            if info['dir'] == variant_dir:
                variant_name = name
                target_folder = info.get('target_folder')
                break
        
        if not variant_name or not target_folder:
            print(f"No target folder specified for {variant_dir}")
            return None
            
        # Look for the specific target folder
        target_path = os.path.join(variant_dir, target_folder)
        if os.path.exists(target_path):
            print(f"Found target folder: {target_path}")
            return target_path
        else:
            print(f"Target folder not found: {target_path}")
            
            # List available folders for debugging
            available = [d for d in os.listdir(variant_dir) 
                       if os.path.isdir(os.path.join(variant_dir, d))]
            print(f"Available folders in {variant_dir}: {available}")
            return None
    
    def load_loss_data(self, run_dir, pair_idx=0):
        """Load loss data and solution data for a specific pair from a run directory"""
        if not run_dir or not os.path.exists(run_dir):
            return None
            
        # Look for pair directories
        pair_dirs = [d for d in os.listdir(run_dir) 
                    if d.startswith('pair_') and os.path.isdir(os.path.join(run_dir, d))]
        
        if not pair_dirs:
            print(f"No pair directories found in: {run_dir}")
            return None
            
        # Use the specified pair (default first pair)
        if pair_idx >= len(pair_dirs):
            pair_idx = 0
            
        pair_dir = os.path.join(run_dir, pair_dirs[pair_idx])
        
        # Load loss histories from JSON if available
        loss_file = os.path.join(pair_dir, 'loss_histories.json')
        if os.path.exists(loss_file):
            try:
                with open(loss_file, 'r') as f:
                    data = json.load(f)
                
                # Extract M and Gamma from pair directory name
                pair_name = pair_dirs[pair_idx]
                parts = pair_name.split('_')
                M = float(parts[2][1:])  # Extract M from "M5.0"
                Gamma = float(parts[3][5:])  # Extract Gamma from "Gamma0.1"
                
                # Generate chi grid for solution (same as in training)
                chi_max = compute_chi_max(M, Gamma)
                chi_min = 0.0
                chi = np.linspace(chi_min, chi_max, 256)
                
                # Calculate analytical solution
                h_ana = h_analytical(chi, M)
                
                # Try to load PINN solution from solution_data.json
                h_pinn = None
                solution_file = os.path.join(pair_dir, 'solution_data.json')
                if os.path.exists(solution_file):
                    try:
                        with open(solution_file, 'r') as f:
                            solution_data = json.load(f)
                        h_pinn = np.array(solution_data['h_pinn'])
                        chi = np.array(solution_data['chi'])
                        print(f"Loaded PINN solution from {solution_file}")
                    except Exception as e:
                        print(f"Could not load solution from {solution_file}: {e}")
                        # Create placeholder if loading fails
                        h_pinn = h_ana + 0.05 * np.sin(2 * np.pi * chi / chi_max) * np.exp(-2 * chi / chi_max)
                else:
                    print(f"No solution_data.json found in {pair_dir}, using placeholder")
                    # Create placeholder if no solution file exists
                    h_pinn = h_ana + 0.05 * np.sin(2 * np.pi * chi / chi_max) * np.exp(-2 * chi / chi_max)
                
                return {
                    'total_loss': data.get('total_loss', []),
                    'ode_loss': data.get('ode_loss', []),
                    'boundary_loss': data.get('boundary_loss', []),
                    'integral_loss': data.get('integral_loss', []),
                    'error_history': data.get('error_history', []),
                    'epochs': list(range(len(data.get('total_loss', [])))),
                    'M': M,
                    'Gamma': Gamma,
                    'chi': chi,
                    'h_analytical': h_ana,
                    'h_pinn': h_pinn,
                    'chi_max': chi_max,
                    'pair_dir': pair_dir
                }
            except Exception as e:
                print(f"Error loading {loss_file}: {e}")
        
        # Fallback: try to load from numpy files or other formats
        print(f"No loss_histories.json found in {pair_dir}")
        return None
    
    def create_comparison_plots(self, pair_idx=0, save_dir="Validation_analytical_PINNs_best_grid_search_Loss_comparison"):
        """Create 3x2 comparison plots with loss components, error history, and solution comparison"""
        
        # Create save directory
        os.makedirs(save_dir, exist_ok=True)
        
        # Load data for all variants
        variant_data = {}
        for variant_name, variant_info in self.variants.items():
            run_dir = self.find_latest_run_dir(variant_info['dir'])
            if run_dir:
                data = self.load_loss_data(run_dir, pair_idx)
                if data:
                    variant_data[variant_name] = {
                        'data': data,
                        'style': variant_info
                    }
                    print(f"Loaded data for {variant_name} from {run_dir}")
                else:
                    print(f"Failed to load data for {variant_name}")
            else:
                print(f"No run directory found for {variant_name}")
        
        if not variant_data:
            print("No data loaded. Cannot create plots.")
            return
        
        # Create 3x2 subplot figure
        fig, axes = plt.subplots(3, 2, figsize=(16, 18))
        #fig.suptitle(f'PINN Comparison - Pair {pair_idx + 1}', fontsize=16, fontweight='bold')
        
        # Define subplot layout (matching bar plot order)
        # axes[0,0]: Solution Comparison + Okwen Reference
        # axes[0,1]: Error History (PINN vs Analytical)
        # axes[1,0]: Residual Loss
        # axes[1,1]: Boundary Loss
        # axes[2,0]: Integral Loss
        # axes[2,1]: Total Loss
        
        # [0,0] Solution Comparison
        ax_sol = axes[0, 0]
        first_variant_name = list(variant_data.keys())[0]
        first_data = variant_data[first_variant_name]['data']
        M = first_data['M']
        Gamma = first_data['Gamma']
        chi = first_data['chi']
        
        ax_sol.plot(chi, h_analytical(chi, M), "k-", linewidth=2.5, label="Analytical", alpha=0.8)
        
        # Okwen point
        chi_max_okwen = compute_chi_max(M, Gamma)
        is_okwen_valid = (5.0 < M < 20.0) and (0.5 < Gamma < 50.0)
        if is_okwen_valid:
            ax_sol.plot(chi_max_okwen, 1.0, "o", color="gray", markersize=8, markerfacecolor="gray", 
                          markeredgecolor="black", label="Okwen χ_max")
        
        for variant_name, variant_info in variant_data.items():
            data = variant_info['data']
            style = variant_info['style']
            h_pinn = data.get('h_pinn', None)
            if h_pinn is not None:
                ax_sol.plot(chi, h_pinn, color=style['color'], linestyle=style['linestyle'], 
                          linewidth=2.0, label=style['label'], alpha=0.8)
        
        ax_sol.set_xlabel("χ", fontsize=11)
        ax_sol.set_ylabel("h(χ)", fontsize=11)
        ax_sol.set_title(f"Solution Comparison (M={M}, Γ={Gamma})", fontsize=13, fontweight='bold')
        ax_sol.grid(True, alpha=0.3)
        ax_sol.legend(loc='best', fontsize=8)
        ax_sol.set_ylim([-0.1, 1.1])
        
        # [0,1] Error History
        ax_err = axes[0, 1]
        for variant_name, variant_info in variant_data.items():
            data = variant_info['data']
            style = variant_info['style']
            if 'error_history' in data and len(data['error_history']) > 0:
                epochs = data['epochs']
                errors = data['error_history']
                ax_err.plot(epochs, errors, color=style['color'], linestyle=style['linestyle'],
                          linewidth=2.0, label=style['label'], alpha=0.8)
        
        ax_err.set_yscale('log')
        ax_err.set_xlabel('Epoch', fontsize=11)
        ax_err.set_ylabel(r"$L_2(h_{\mathrm{PINN}}-h_{\mathrm{analytical}})$", fontsize=11)
        ax_err.set_title('Error History (PINN vs Analytical)', fontsize=13, fontweight='bold')
        ax_err.grid(True, which="both", alpha=0.3)
        ax_err.legend(loc='best', fontsize=9)
        
        # Plot loss components (remaining 4 subplots)
        loss_components = [
            ('ode_loss', 'Residual Loss', axes[1,0]),
            ('boundary_loss', 'Boundary Loss', axes[1,1]),
            ('integral_loss', 'Integral Loss', axes[2,0]),
            ('total_loss', 'Total Loss', axes[2,1])
        ]
        
        for component, title, ax in loss_components:
            for variant_name, variant_info in variant_data.items():
                data = variant_info['data']
                style = variant_info['style']
                
                if component in data and len(data[component]) > 0:
                    epochs = data['epochs']
                    losses = data[component]
                    
                    ax.plot(epochs, losses, 
                           color=style['color'],  # Use variant color instead of component color
                           linestyle=style['linestyle'],
                           linewidth=2.0,
                           label=style['label'],
                           alpha=0.8)
            
            ax.set_yscale('log')
            ax.set_xlabel('Epoch', fontsize=11)
            ax.set_ylabel('Loss', fontsize=11)
            ax.set_title(title, fontsize=13, fontweight='bold')
            ax.grid(True, which="both", alpha=0.3)
            
            # Add legend to every subplot
            ax.legend(loc='best', fontsize=9)
        
        # Adjust layout to prevent overlap
        plt.tight_layout(rect=[0, 0, 1, 0.96])  # Make room for suptitle
        
        # Save the combined plot
        save_path = os.path.join(save_dir, f'pinn_comparison_3x2_pair_{pair_idx + 1}.png')
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close()
        
        print(f"Saved 3x2 comparison plot to {save_path}")
        
        # Also create summary table
        self.create_summary_table(variant_data, pair_idx, save_dir)
        
        # Create bar plots for final losses
        self.create_bar_plots(variant_data, pair_idx, save_dir)
        
        print(f"\n📊 All comparison plots saved to: {save_dir}")
    
    def create_bar_plots(self, variant_data, pair_idx, save_dir):
        """Create simple 3x2 bar plot layout"""
        fig, axes = plt.subplots(3, 2, figsize=(16, 12))
        
        # [0,0] Solution Comparison
        ax_sol = axes[0, 0]
        first_variant_name = list(variant_data.keys())[0]
        first_data = variant_data[first_variant_name]['data']
        M = first_data['M']
        Gamma = first_data['Gamma']
        chi = first_data['chi']
        
        ax_sol.plot(chi, h_analytical(chi, M), "k-", linewidth=2.5, label="Analytical", alpha=0.8)
        
        # Okwen point
        chi_max_okwen = compute_chi_max(M, Gamma)
        is_okwen_valid = (5.0 < M < 20.0) and (0.5 < Gamma < 50.0)
        if is_okwen_valid:
            ax_sol.plot(chi_max_okwen, 1.0, "o", color="gray", markersize=8, markerfacecolor="gray", 
                          markeredgecolor="black", label="Okwen χ_max")
        
        for variant_name, variant_info in variant_data.items():
            data = variant_info['data']
            style = variant_info['style']
            h_pinn = data.get('h_pinn', None)
            if h_pinn is not None:
                ax_sol.plot(chi, h_pinn, color=style['color'], linestyle=style['linestyle'], 
                          linewidth=2.0, label=style['label'], alpha=0.8)
        
        ax_sol.set_xlabel("χ", fontsize=11)
        ax_sol.set_ylabel("h(χ)", fontsize=11)
        ax_sol.set_title(f"Solution Comparison (M={M}, Γ={Gamma})", fontsize=13, fontweight='bold')
        ax_sol.grid(True, alpha=0.3)
        ax_sol.legend(loc='best', fontsize=8)
        ax_sol.set_ylim([-0.1, 1.1])
        
        # [0,1] Error History (bar chart)
        ax_err = axes[0, 1]
        final_errs, err_labels, err_colors = [], [], []
        for variant_name, variant_info in variant_data.items():
            data = variant_info['data']
            style = variant_info['style']
            if 'error_history' in data and len(data['error_history']) > 0:
                final_errs.append(data['error_history'][-1])
                err_labels.append(style['label'])
                err_colors.append(style['color'])
        
        if final_errs:
            x = np.arange(len(final_errs))
            ax_err.bar(x, final_errs, color=err_colors, alpha=0.9)
            ax_err.set_yscale('log')
            ax_err.set_title('Error History (PINN vs Analytical)', fontsize=13, fontweight='bold')
            ax_err.set_xlabel('')
            ax_err.set_ylabel('Final Error', fontsize=11)
            ax_err.set_xticks(x)
            ax_err.set_xticklabels(err_labels, rotation=45, ha='right', fontsize=8)
            ax_err.grid(True, which='both', alpha=0.3)
        
        # [1,0] Residual Loss
        ax_ode = axes[1, 0]
        self._create_loss_bar_chart(ax_ode, variant_data, 'ode_loss', 'Residual Loss')
        
        # [1,1] Boundary Loss
        ax_boundary = axes[1, 1]
        self._create_loss_bar_chart(ax_boundary, variant_data, 'boundary_loss', 'Boundary Loss')
        
        # [2,0] Integral Loss
        ax_integral = axes[2, 0]
        self._create_loss_bar_chart(ax_integral, variant_data, 'integral_loss', 'Integral Loss')
        
        # [2,1] Total Loss
        ax_total = axes[2, 1]
        self._create_loss_bar_chart(ax_total, variant_data, 'total_loss', 'Total Loss')
        
        plt.tight_layout()
        save_path = os.path.join(save_dir, f'bar_comparison_3x2_pair_{pair_idx + 1}.png')
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved bar plot to {save_path}")
    
    def _create_loss_bar_chart(self, ax, variant_data, loss_key, title):
        """Helper method to create individual loss bar charts"""
        values, labels, colors = [], [], []
        for variant_name, variant_info in variant_data.items():
            data = variant_info['data']
            style = variant_info['style']
            if loss_key in data and len(data[loss_key]) > 0:
                values.append(data[loss_key][-1])
                labels.append(style['label'])
                colors.append(style['color'])
        
        if values:
            x = np.arange(len(values))
            ax.bar(x, values, color=colors, alpha=0.9)
            ax.set_yscale('log')
            ax.set_title(title, fontsize=13, fontweight='bold')
            ax.set_xlabel('')
            ax.set_ylabel('Final Loss', fontsize=11)
            ax.set_xticks(x)
            ax.set_xticklabels(labels, rotation=45, ha='right', fontsize=8)
            ax.grid(True, which='both', alpha=0.3)
    
    def create_summary_table(self, variant_data, pair_idx, save_dir):
        """Create a summary table comparing final losses"""
        summary_data = []
        
        for variant_name, variant_info in self.variants.items():
            run_dir = self.find_latest_run_dir(variant_info['dir'])
            if run_dir:
                data = self.load_loss_data(run_dir, pair_idx=0)  # Use first pair
                if data:
                    final_losses = {}
                    for component in ['ode_loss', 'boundary_loss', 'integral_loss', 'total_loss']:
                        if component in data and len(data[component]) > 0:
                            final_losses[component] = data[component][-1]
                        else:
                            final_losses[component] = None
                    
                    summary_data.append({
                        'Variant': variant_name,
                        'Final ODE Loss': final_losses.get('ode_loss'),
                        'Final Boundary Loss': final_losses.get('boundary_loss'),
                        'Final Integral Loss': final_losses.get('integral_loss'),
                        'Final Total Loss': final_losses.get('total_loss')
                    })
        
        if summary_data:
            df = pd.DataFrame(summary_data)
            save_path = os.path.join(save_dir, 'loss_summary_table.csv')
            df.to_csv(save_path, index=False)
            print(f"Saved summary table to {save_path}")
            print("Summary Table:")
            print(df.to_string(index=False, float_format='%.2e'))

    def _sorted_variant_items(self):
        """Stable ordering: by layers then activation (gelu, swish, tanh) if present."""
        activation_order = ["gelu", "swish", "tanh"]
        
        def layers_key(kv):
            return kv[1].get("layers", "")
        
        def activation_key(kv):
            return activation_order.index(kv[1].get("activation", "")) if kv[1].get("activation", "") in activation_order else 999
        
        items = list(self.variants.items())
        items.sort(key=lambda kv: (layers_key(kv), activation_key(kv)))
        return items

def main():
    """Main function to run the comparison"""
    print("PINN Loss Component Comparison Tool")
    print("=" * 50)
    
    # Define output directory
    output_dir = "Validation_analytical_PINNs_best_grid_search_Loss_comparison"
    
    # Remove existing directory if it exists
    if os.path.exists(output_dir):
        print(f"Removing existing directory: {output_dir}")
        shutil.rmtree(output_dir)
    
    # Create fresh directory
    print(f"Creating fresh directory: {output_dir}")
    os.makedirs(output_dir, exist_ok=True)
    
    # Create comparator
    comparator = LossComponentComparator()
    
    # Create comparison plots for all pairs (you can specify pair_idx)
    comparator.create_comparison_plots(pair_idx=0)  # Use first pair
    comparator.create_comparison_plots(pair_idx=1)  # Use second pair if available
    
    print("\nComparison completed successfully!")
    print(f"All outputs saved to: {output_dir}")

if __name__ == "__main__":
    main()
