# -*- coding: utf-8 -*-
"""
Created on Wed Feb 04 17:43:19 2026

@author: jpauya1
"""



"""
Comparison of Loss Components and Solutions Across Different PINN Base Case Variants
=============================================================================

This script reads loss histories and solution data from JSON files generated by:
1. Validation_analytical_PINNs_base_case.py
2. Validation_analytical_PINNs_EMA_adaptive_weighted_loss_base_case.py  
3. Validation_analytical_PINNs_gradient_based_adaptive_weighted_loss_base_case.py

And creates comparison plots showing:
- Row 0: ODE/Residual Loss, Boundary Loss
- Row 1: Integral Loss, Total Loss
- Row 2: Error History + Okwen Point, Solution Comparison (Analytical + Okwen + PINN)

Each component uses same color, different linestyle per variant.
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
from pathlib import Path
import matplotlib as mpl
import shutil


# Set up matplotlib for better plots
mpl.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 11,
    'figure.titlesize': 16
})

# Analytical solution function
def h_analytical(chi, M):
    """
    Piecewise analytical solution (Gamma does NOT appear in this closed form):
      h = 0                                for chi <= 2/M
      h = (M - sqrt(2M/chi)) / (M - 1)     for 2/M < chi < 2M
      h = 1                                for chi >= 2M
    """
    chi = np.asarray(chi, dtype=float)
    h = np.zeros_like(chi)

    left = chi <= (2.0 / M)
    mid = (chi > (2.0 / M)) & (chi < (2.0 * M))
    right = chi >= (2.0 * M)

    h[left] = 0.0
    h[mid] = (M - np.sqrt(2.0 * M / chi[mid])) / (M - 1.0)
    h[right] = 1.0
    return h

# Okwen correlation
def compute_chi_max(M, Gamma):
    return (0.0324 * M - 0.0952) * Gamma + (0.1778 * M + 5.9682) * (Gamma ** 0.5) + 1.6962 * M - 3.0472

class LossComponentComparator:
    def __init__(self):
        self.variants = {
            'Base Case': {
                'dir': 'runs_validation_PINN_base_case',
                'color': 'blue',
                'linestyle': '-',
                'marker': None,
                'label': 'Base Case'
            },
            'Gradient-Based Weighted Loss': {
                'dir': 'runs_validation_PINN_EMA_adaptive_weighted_loss_base_case',
                'color': 'red',
                'linestyle': '-',
                'marker': None,
                'label': 'EMA Gradient-Based Weighted Loss'
            },
            'Gradient-Based Weighted Loss + LBFGS': {
                'dir': 'runs_validation_PINN_gradient_based_adaptive_weighted_loss_base_case',
                'color': 'green', 
                'linestyle': '-',
                'marker': None,
                'label': 'Gradient-Based Weighted Loss'
            }
        }
        
        self.component_colors = {
            'ode': '#1f77b4',      # Blue
            'boundary': '#ff7f0e',  # Orange  
            'integral': '#2ca02c',  # Green
            'total': '#8b008b'       # Violet (Dark Magenta)
        }
        
    def find_latest_run_dir(self, variant_dir):
        """Find the most recent run directory for a variant"""
        if not os.path.exists(variant_dir):
            print(f"Directory not found: {variant_dir}")
            return None
            
        # Look for subdirectories that contain pair directories
        subdirs = [d for d in os.listdir(variant_dir) 
                  if os.path.isdir(os.path.join(variant_dir, d))]
        
        if not subdirs:
            print(f"No run directories found in: {variant_dir}")
            return None
            
        # Return the most recent (assuming sorted by name/date)
        latest_dir = sorted(subdirs)[-1]
        return os.path.join(variant_dir, latest_dir)
    
    def load_loss_data(self, run_dir, pair_idx=0):
        """Load loss data and solution data for a specific pair from a run directory"""
        if not run_dir or not os.path.exists(run_dir):
            return None
            
        # Look for pair directories
        pair_dirs = [d for d in os.listdir(run_dir) 
                    if d.startswith('pair_') and os.path.isdir(os.path.join(run_dir, d))]
        
        if not pair_dirs:
            print(f"❌ No pair directories found in: {run_dir}")
            return None
            
        # Use the specified pair (default first pair)
        if pair_idx >= len(pair_dirs):
            pair_idx = 0
            
        pair_dir = os.path.join(run_dir, pair_dirs[pair_idx])
        
        # Load loss histories from JSON if available
        loss_file = os.path.join(pair_dir, 'loss_histories.json')
        if os.path.exists(loss_file):
            try:
                with open(loss_file, 'r') as f:
                    data = json.load(f)
                
                # Extract M and Gamma from pair directory name
                pair_name = pair_dirs[pair_idx]
                parts = pair_name.split('_')
                M = float(parts[2][1:])  # Extract M from "M5.0"
                Gamma = float(parts[3][5:])  # Extract Gamma from "Gamma0.1"
                
                # Generate chi grid for solution (same as in training)
                chi_max = compute_chi_max(M, Gamma)
                chi_min = 0.0
                chi = np.linspace(chi_min, chi_max, 256)
                
                # Calculate analytical solution
                h_ana = h_analytical(chi, M)
                
                # Try to load PINN solution from solution_data.json
                h_pinn = None
                solution_file = os.path.join(pair_dir, 'solution_data.json')
                if os.path.exists(solution_file):
                    try:
                        with open(solution_file, 'r') as f:
                            solution_data = json.load(f)
                        h_pinn = np.array(solution_data['h_pinn'])
                        chi = np.array(solution_data['chi'])
                        print(f"Loaded PINN solution from {solution_file}")
                    except Exception as e:
                        print(f"Could not load solution from {solution_file}: {e}")
                        # Create placeholder if loading fails
                        h_pinn = h_ana + 0.05 * np.sin(2 * np.pi * chi / chi_max) * np.exp(-2 * chi / chi_max)
                else:
                    print(f"No solution_data.json found in {pair_dir}, using placeholder")
                    # Create placeholder if no solution file exists
                    h_pinn = h_ana + 0.05 * np.sin(2 * np.pi * chi / chi_max) * np.exp(-2 * chi / chi_max)
                
                return {
                    'total_loss': data.get('total_loss', []),
                    'ode_loss': data.get('ode_loss', []),
                    'boundary_loss': data.get('boundary_loss', []),
                    'integral_loss': data.get('integral_loss', []),
                    'error_history': data.get('error_history', []),
                    'epochs': list(range(len(data.get('total_loss', [])))),
                    'M': M,
                    'Gamma': Gamma,
                    'chi': chi,
                    'h_analytical': h_ana,
                    'h_pinn': h_pinn,
                    'chi_max': chi_max,
                    'pair_dir': pair_dir
                }
            except Exception as e:
                print(f"Error loading {loss_file}: {e}")
        
        # Fallback: try to load from numpy files or other formats
        print(f"No loss_histories.json found in {pair_dir}")
        return None
    
    def create_comparison_plots(self, pair_idx=0, save_dir="Validation_analytical_PINNs_Loss_comparison"):
        """Create 3x2 comparison plots with loss components, error history, and solution comparison"""
        
        # Create save directory
        os.makedirs(save_dir, exist_ok=True)
        
        # Load data for all variants
        variant_data = {}
        for variant_name, variant_info in self.variants.items():
            run_dir = self.find_latest_run_dir(variant_info['dir'])
            if run_dir:
                data = self.load_loss_data(run_dir, pair_idx)
                if data:
                    variant_data[variant_name] = {
                        'data': data,
                        'style': variant_info
                    }
                    print(f"Loaded data for {variant_name} from {run_dir}")
                else:
                    print(f"Failed to load data for {variant_name}")
            else:
                print(f"No run directory found for {variant_name}")
        
        if not variant_data:
            print("No data loaded. Cannot create plots.")
            return
        
        # Create 3x2 subplot figure
        fig, axes = plt.subplots(3, 2, figsize=(16, 18))
        fig.suptitle(f'PINN Comparison - Pair {pair_idx + 1}', fontsize=16, fontweight='bold')
        
        # Define subplot layout
        # axes[0,0]: ODE/Residual Loss
        # axes[0,1]: Boundary Loss
        # axes[1,0]: Integral Loss  
        # axes[1,1]: Total Loss
        # axes[2,0]: Solution Comparison + Okwen Reference
        # axes[2,1]: Error History (PINN vs Analytical)
        
        # Plot loss components (top 4 subplots)
        loss_components = [
            ('ode_loss', 'Residual Loss', axes[0,0]),
            ('boundary_loss', 'Boundary Loss', axes[0,1]),
            ('integral_loss', 'Integral Loss', axes[1,0]),
            ('total_loss', 'Total Loss', axes[1,1])
        ]
        
        for component, title, ax in loss_components:
            for variant_name, variant_info in variant_data.items():
                data = variant_info['data']
                style = variant_info['style']
                
                if component in data and len(data[component]) > 0:
                    epochs = data['epochs']
                    losses = data[component]
                    
                    ax.plot(epochs, losses, 
                           color=style['color'],  # Use variant color instead of component color
                           linestyle=style['linestyle'],
                           linewidth=2.0,
                           label=style['label'],
                           alpha=0.8)
            
            ax.set_yscale('log')
            ax.set_xlabel('Epoch', fontsize=11)
            ax.set_ylabel('Loss', fontsize=11)
            ax.set_title(title, fontsize=13, fontweight='bold')
            ax.grid(True, which="both", alpha=0.3)
            
            # Add legend to every subplot
            ax.legend(loc='best', fontsize=9)
        
        # Plot solution comparison (axes[2,0])
        # Get the first variant's data for chi and analytical solution
        first_variant = list(variant_data.values())[0]
        data = first_variant['data']
        chi = data['chi']  # Use the loaded chi grid
        M = data['M']
        Gamma = data['Gamma']
        
        # Calculate analytical solution using the loaded chi grid
        h_ana = h_analytical(chi, M)
        
        # Plot analytical solution
        axes[2,0].plot(chi, h_ana, 'k-', linewidth=2.5, label='Analytical', alpha=0.8)
        
        # Plot Okwen point conditionally
        chi_max_okwen = compute_chi_max(M, Gamma)
        
        # Check if M and Gamma are within valid range for Okwen correlation
        # Based on the correlation range: 0.5 <= M <= 10, 0.1 <= Gamma <= 0.5
        is_okwen_valid = (0.5 < M < 10.0) and (0.1 < Gamma < 0.5)
        
        if is_okwen_valid:
            axes[2,0].plot(chi_max_okwen, 1.0, 'o', color='gray', markersize=8, markerfacecolor='gray', 
                          markeredgecolor='black', label='Okwen χ_max')
            print(f"Okwen point plotted for M={M}, Γ={Gamma} (within valid range)")
        else:
            print(f"Okwen point NOT plotted for M={M}, Γ={Gamma} (outside valid range: 0.5≤M≤10, 0.1≤Γ≤0.5)")
        
        # Plot PINN solutions for each variant
        for variant_name, variant_info in variant_data.items():
            data = variant_info['data']
            style = variant_info['style']
            h_pinn = data['h_pinn']
            
            if h_pinn is not None:
                # Use the chi grid from this variant's solution data
                variant_chi = data['chi']
                
                axes[2,0].plot(variant_chi, h_pinn, 
                              color=style['color'],
                              linestyle=style['linestyle'],
                              linewidth=2.0,
                              label=style['label'],
                              alpha=0.8)
            else:
                print(f"No PINN solution available for {variant_name}")
        
        axes[2,0].set_xlabel('χ', fontsize=11)
        axes[2,0].set_ylabel('h(χ)', fontsize=11)
        axes[2,0].set_title(f'PINN Solution Comparison (M={M}, Γ={Gamma})', fontsize=13, fontweight='bold')
        axes[2,0].grid(True, alpha=0.3)
        axes[2,0].legend(loc='best', fontsize=9)
        axes[2,0].set_ylim([-0.1, 1.1])
        
        # Plot error history (axes[2,1])
        for variant_name, variant_info in variant_data.items():
            data = variant_info['data']
            style = variant_info['style']
            
            if 'error_history' in data and len(data['error_history']) > 0:
                epochs = data['epochs']
                errors = data['error_history']
                
                axes[2,1].plot(epochs, errors, 
                              color=style['color'],
                              linestyle=style['linestyle'],
                              linewidth=2.0,
                              label=style['label'],
                              alpha=0.8)
        
        axes[2,1].set_yscale('log')
        axes[2,1].set_xlabel('Epoch', fontsize=11)
        axes[2,1].set_ylabel(r"$L_2(h_{\mathrm{PINN}}-h_{\mathrm{analytical}})$", fontsize=11)
        axes[2,1].set_title('Error History (PINN vs Analytical)', fontsize=13, fontweight='bold')
        axes[2,1].grid(True, which="both", alpha=0.3)
        axes[2,1].legend(loc='best', fontsize=9)
        
        # Adjust layout to prevent overlap
        plt.tight_layout(rect=[0, 0, 1, 0.96])  # Make room for suptitle
        
        # Save the combined plot
        save_path = os.path.join(save_dir, f'pinn_comparison_3x2_pair_{pair_idx + 1}.png')
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close()
        
        print(f"Saved 3x2 comparison plot to {save_path}")
        
        # Also create summary table
        self.create_summary_table(variant_data, pair_idx, save_dir)
        
        print(f"All comparison plots saved to: {save_dir}")
    
    def create_summary_table(self, variant_data, pair_idx, save_dir):
        """Create a summary table comparing final losses"""
        summary_data = []
        
        for variant_name, variant_info in self.variants.items():
            run_dir = self.find_latest_run_dir(variant_info['dir'])
            if run_dir:
                data = self.load_loss_data(run_dir, pair_idx=0)  # Use first pair
                if data:
                    final_losses = {}
                    for component in ['ode_loss', 'boundary_loss', 'integral_loss', 'total_loss']:
                        if component in data and len(data[component]) > 0:
                            final_losses[component] = data[component][-1]
                        else:
                            final_losses[component] = None
                    
                    summary_data.append({
                        'Variant': variant_name,
                        'Final ODE Loss': final_losses.get('ode_loss'),
                        'Final Boundary Loss': final_losses.get('boundary_loss'),
                        'Final Integral Loss': final_losses.get('integral_loss'),
                        'Final Total Loss': final_losses.get('total_loss')
                    })
        
        if summary_data:
            df = pd.DataFrame(summary_data)
            save_path = os.path.join(save_dir, 'loss_summary_table.csv')
            df.to_csv(save_path, index=False)
            print(f"Saved summary table to {save_path}")
            print("Summary Table:")
            print(df.to_string(index=False, float_format='%.2e'))

def main():
    """Main function to run the comparison"""
    print("PINN Loss Component Comparison Tool")
    print("=" * 50)
    
    # Define output directory
    output_dir = "Validation_analytical_PINNs_Loss_comparison"
    
    # Remove existing directory if it exists
    if os.path.exists(output_dir):
        print(f"Removing existing directory: {output_dir}")
        shutil.rmtree(output_dir)
    
    # Create fresh directory
    print(f"Creating fresh directory: {output_dir}")
    os.makedirs(output_dir, exist_ok=True)
    
    # Create comparator
    comparator = LossComponentComparator()
    
    # Create comparison plots for all pairs (you can specify pair_idx)
    comparator.create_comparison_plots(pair_idx=0)  # Use first pair
    comparator.create_comparison_plots(pair_idx=1)  # Use second pair if available
    
    print("\nComparison completed successfully!")
    print(f"All outputs saved to: {output_dir}")

if __name__ == "__main__":
    main()
