# -*- coding: utf-8 -*-
"""
Created on Wed Feb 04 17:43:19 2026

@author: jpauya1
"""



"""
Comparison of Loss Components and Solutions Across Different PINN Grid Search Variants
=============================================================================

This script reads loss histories and solution data from JSON files generated by:
1. Validation_analytical_PINNs_base_case_grid_search.py

And creates comparison plots showing:
- Row 0: ODE/Residual Loss, Boundary Loss
- Row 1: Integral Loss, Total Loss
- Row 2: Error History + Okwen Point, Solution Comparison (Analytical + Okwen + PINN)

Each component uses same color, different linestyle per variant.
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
from pathlib import Path
import matplotlib as mpl
import shutil
import matplotlib.patches as mpatches


# Set up matplotlib for better plots
mpl.rcParams.update({
    'font.size': 16,
    'axes.titlesize': 18,
    'axes.labelsize': 16,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 14,
    'figure.titlesize': 18
})

# Analytical solution function
def h_analytical(chi, M):
    """
    Piecewise analytical solution (Gamma does NOT appear in this closed form):
      h = 0                                for chi <= 2/M
      h = (M - sqrt(2M/chi)) / (M - 1)     for 2/M < chi < 2M
      h = 1                                for chi >= 2M
    """
    chi = np.asarray(chi, dtype=float)
    h = np.zeros_like(chi)

    left = chi <= (2.0 / M)
    mid = (chi > (2.0 / M)) & (chi < (2.0 * M))
    right = chi >= (2.0 * M)

    h[left] = 0.0
    h[mid] = (M - np.sqrt(2.0 * M / chi[mid])) / (M - 1.0)
    h[right] = 1.0
    return h

# Okwen correlation
def compute_chi_max(M, Gamma):
    return (0.0324 * M - 0.0952) * Gamma + (0.1778 * M + 5.9682) * (Gamma ** 0.5) + 1.6962 * M - 3.0472

def is_okwen_valid(M, Gamma):
    """
    Check if M and Gamma values are within the valid range for Okwen correlation.
    Based on the correlation range: 5.0 < M < 20.0, 0.5 < Gamma < 50.0
    """
    return (5.0 < M < 20.0) and (0.5 < Gamma < 50.0)

class LossComponentComparator:
    def __init__(self, grid_search_dir="runs_validation_PINN_base_case_grid_search"):
        self.grid_search_dir = grid_search_dir
        self.variants = {}
        
        # Colors by activation function (same as bar plots)
        self.activation_colors = {
            "gelu": "blue",
            "swish": "green", 
            "tanh": "red"
        }
        
        # Linestyles by layer configuration
        self.layer_linestyles = {
            "8,8,8": "-",
            "16,16,16": "--",
            "32,32,32": ":",
        }
        
    def find_run_directories(self):
        if not os.path.exists(self.grid_search_dir):
            print(f"Grid search directory not found: {self.grid_search_dir}")
            return []
        run_dirs = []
        for item in os.listdir(self.grid_search_dir):
            run_path = os.path.join(self.grid_search_dir, item)
            if os.path.isdir(run_path) and item.startswith("run_layers_"):
                run_dirs.append(run_path)
        return sorted(run_dirs)

    def parse_run_name(self, run_dir):
        # "run_layers_[8,8,8]_act_tanh"
        run_name = os.path.basename(run_dir)
        parts = run_name.split("_")
        layers_start_idx = parts.index("layers") + 1
        layers_end_idx = parts.index("act")
        layers_parts = parts[layers_start_idx:layers_end_idx]
        layers_str = "_".join(layers_parts)  # "[8,8,8]"
        activation = parts[layers_end_idx + 1]
        layers_clean = layers_str.replace("[", "").replace("]", "")
        variant_id = f"[{layers_clean}]_{activation}"
        return variant_id, layers_clean, activation
    
    def load_loss_data(self, run_dir, pair_idx=0):
        if not run_dir or not os.path.exists(run_dir):
            return None

        pair_dirs = [
            d for d in os.listdir(run_dir)
            if d.startswith("pair_") and os.path.isdir(os.path.join(run_dir, d))
        ]
        if not pair_dirs:
            print(f"No pair directories found in: {run_dir}")
            return None

        pair_dirs = sorted(pair_dirs)
        if pair_idx >= len(pair_dirs):
            pair_idx = 0

        pair_dirname = pair_dirs[pair_idx]
        pair_dir = os.path.join(run_dir, pair_dirname)

        loss_file = os.path.join(pair_dir, "loss_histories.json")
        if not os.path.exists(loss_file):
            return None

        try:
            with open(loss_file, "r") as f:
                data = json.load(f)

            # parse M & Gamma from "pair_1_M5.0_Gamma0.1"
            parts = pair_dirname.split("_")
            M = None
            Gamma = None
            for p in parts:
                if p.startswith("M"):
                    M = float(p[1:])
                if p.startswith("Gamma"):
                    Gamma = float(p[5:])
            if M is None or Gamma is None:
                raise ValueError(f"Could not parse M/Gamma from {pair_dirname}")

            # solution data
            h_pinn = None
            chi = None
            solution_file = os.path.join(pair_dir, "solution_data.json")
            if os.path.exists(solution_file):
                try:
                    with open(solution_file, "r") as f:
                        solution_data = json.load(f)
                    h_pinn = np.array(solution_data["h_pinn"], dtype=float)
                    chi = np.array(solution_data["chi"], dtype=float)
                    print(f"Loaded PINN solution from {solution_file}")
                except Exception as e:
                    print(f"Could not load solution from {solution_file}: {e}")

            if chi is None:
                chi_max = compute_chi_max(M, Gamma)
                chi = np.linspace(0.0, chi_max, 256)

            h_ana = h_analytical(chi, M)

            if h_pinn is None:
                chi_max = compute_chi_max(M, Gamma)
                h_pinn = h_ana + 0.05 * np.sin(2 * np.pi * chi / chi_max) * np.exp(-2 * chi / chi_max)

            total_loss = data.get("total_loss", [])
            epochs = list(range(len(total_loss))) if isinstance(total_loss, list) else []

            return {
                "total_loss": data.get("total_loss", []),
                "ode_loss": data.get("ode_loss", []),
                "boundary_loss": data.get("boundary_loss", []),
                "integral_loss": data.get("integral_loss", []),
                "error_history": data.get("error_history", []),
                "epochs": epochs,
                "M": M,
                "Gamma": Gamma,
                "chi": chi,
                "h_analytical": h_ana,
                "h_pinn": h_pinn,
                "chi_max": compute_chi_max(M, Gamma),
                "pair_dir": pair_dir,
            }

        except Exception as e:
            print(f"Error loading {loss_file}: {e}")
            return None

    def load_all_variants(self, pair_idx=0):
        run_dirs = self.find_run_directories()
        for run_dir in run_dirs:
            variant_id, layers_str, activation = self.parse_run_name(run_dir)
            data = self.load_loss_data(run_dir, pair_idx)
            if data:
                # Use activation-based color and layer-based linestyle
                color = self.activation_colors.get(activation, "black")
                linestyle = self.layer_linestyles.get(layers_str, "-")
                
                self.variants[variant_id] = {
                    "data": data,
                    "style": {
                        "color": color,
                        "linestyle": linestyle,
                        "label": f"[{layers_str}] | {activation}",
                    },
                    "layers": layers_str,
                    "activation": activation,
                    "run_dir": run_dir,
                }
                print(f"Loaded data for {variant_id}")
            else:
                print(f"Failed to load data for {variant_id}")

    def create_comparison_plots(self, pair_idx=0, save_dir="Validation_analytical_PINNs_base_case_grid_search_Loss_comparison"):
        """Create 3x2 comparison plots with loss components, error history, and solution comparison"""
        
        # Create save directory only if it doesn't exist
        if not os.path.exists(save_dir):
            os.makedirs(save_dir, exist_ok=True)
        
        self.variants = {}
        self.load_all_variants(pair_idx)

        if not self.variants:
            print("No data loaded for comparison")
            return

        # Existing bar figure (kept)
        self.create_bar_plot_layout(pair_idx, save_dir)

        # NEW: line figure
        self.create_line_plot_layout(pair_idx, save_dir)

        self.create_summary_table(save_dir)

    def _sorted_variant_items(self):
        """Stable ordering: by layers then activation (gelu, swish, tanh) if present."""
        activation_order = ["gelu", "swish", "tanh"]

        def layers_key(layers_str):
            try:
                return tuple(int(x.strip()) for x in layers_str.split(","))
            except Exception:
                return (9999,)

        def activation_key(act):
            return activation_order.index(act) if act in activation_order else 999

        items = list(self.variants.items())
        items.sort(key=lambda kv: (layers_key(kv[1].get("layers", "")), activation_key(kv[1].get("activation", ""))))
        return items

    # ----------------------------- #
    # Existing BAR plot layout
    # ----------------------------- #
    def create_bar_plot_layout(self, pair_idx, save_dir):
        """Create 3x2 bar-plot layout, with only subplot [0,0] slightly taller.
    
        The grid itself remains 3x2. After tight_layout(), only the solution
        comparison axis is manually enlarged a little to compensate for the
        extra x-label / tick-label space taken by subplot [0,1].
        """
    
        activation_colors = {
            "gelu": "blue",
            "swish": "green",
            "tanh": "red",
        }
        activation_order = ["gelu", "swish", "tanh"]
        legend_handles = [
            mpatches.Patch(color=activation_colors[a], label=a)
            for a in activation_order
        ]
    
        variant_items = self._sorted_variant_items()
        if not variant_items:
            print("[WARNING] No variant data available for bar plot layout.")
            return
    
        # Standard 3x2 layout
        fig, axes = plt.subplots(3, 2, figsize=(15, 13))
    
        # No figure title as requested
    
        # --------------------------------------------------
        # [0,0] Solution comparison
        # --------------------------------------------------
        ax_sol = axes[0, 0]
    
        first_variant = variant_items[0][1]
        d0 = first_variant["data"]
        M = d0["M"]
        Gamma = d0["Gamma"]
        chi = d0["chi"]
    
        ax_sol.plot(
            chi,
            h_analytical(chi, M),
            "k-",
            linewidth=2.5,
            label="Analytical",
            alpha=0.8,
        )
    
        # Only plot Okwen point if within valid range
        if is_okwen_valid(M, Gamma):
            chi_max_okwen = compute_chi_max(M, Gamma)
            ax_sol.plot(
                chi_max_okwen,
                1.0,
                "o",
                color="gray",
                markersize=8,
                markerfacecolor="gray",
                markeredgecolor="black",
                label="Okwen χ_max",
            )
    
        for _, info in variant_items:
            data = info["data"]
            style = info.get("style", {})
            layers_str = info.get("layers", "")
            act = info.get("activation", "unknown")
            h_pinn = data.get("h_pinn", None)
    
            if h_pinn is None:
                continue
    
            ax_sol.plot(
                data["chi"],
                h_pinn,
                color=style.get("color", "black"),
                linestyle=style.get("linestyle", "-"),
                linewidth=2.0,
                alpha=0.85,
                label=f"[{layers_str}] | {act}",
            )
    
        ax_sol.set_xlabel("χ", fontsize=14)
        ax_sol.set_ylabel("h(χ)", fontsize=14)
        ax_sol.set_title(
            f"PINN Solution (M={M}, Γ={Gamma})",
            fontsize=16
        )
        ax_sol.grid(True, alpha=0.3)
        ax_sol.legend(loc="best", fontsize=10)
        ax_sol.set_ylim([-0.1, 1.1])
    
        # --------------------------------------------------
        # [0,1] Error history bars
        # --------------------------------------------------
        ax_err = axes[0, 1]
        final_errs, err_labels, err_colors = [], [], []
    
        for _, info in variant_items:
            data = info["data"]
            act = info.get("activation", "unknown")
            layers_str = info.get("layers", "")
            eh = data.get("error_history", [])
    
            if eh is None or len(eh) == 0:
                continue
    
            final_errs.append(eh[-1])
            err_labels.append(f"[{layers_str}] | {act}")
            err_colors.append(activation_colors.get(act, "black"))
    
        if final_errs:
            x = np.arange(len(final_errs))
            ax_err.bar(x, final_errs, color=err_colors, alpha=0.9)
            ax_err.set_yscale("log")
            ax_err.set_title(
                "Error History (PINN vs Analytical)",
                fontsize=16
            )
            ax_err.set_xlabel("")
            ax_err.set_ylabel("Final Error", fontsize=14)
            ax_err.set_xticks(x)
            ax_err.set_xticklabels(err_labels, rotation=45, ha="right", fontsize=12)
            ax_err.grid(True, which="both", alpha=0.3)
            ax_err.legend(
                handles=legend_handles,
                title="Activation",
                loc="best",
                fontsize=10,
                title_fontsize=10,
            )
        else:
            ax_err.set_title("Error History (no data)", fontsize=16)
            ax_err.axis("off")
    
        # --------------------------------------------------
        # Helper for loss bars
        # --------------------------------------------------
        def collect_final_values(component_name):
            vals, xlabels, bar_colors = [], [], []
    
            for _, info in variant_items:
                data = info["data"]
                act = info.get("activation", "unknown")
                layers_str = info.get("layers", "")
                series = data.get(component_name, [])
    
                if series is None or len(series) == 0:
                    continue
    
                vals.append(series[-1])
                xlabels.append(f"[{layers_str}] | {act}")
                bar_colors.append(activation_colors.get(act, "black"))
    
            return vals, xlabels, bar_colors
    
        # --------------------------------------------------
        # Remaining 4 bar plots
        # --------------------------------------------------
        bar_components = [
            ("ode_loss", "Residual Loss", axes[1, 0]),
            ("boundary_loss", "Boundary Loss", axes[1, 1]),
            ("integral_loss", "Integral Loss", axes[2, 0]),
            ("total_loss", "Total Loss", axes[2, 1]),
        ]
    
        for component, title, ax in bar_components:
            vals, xlabels, bar_colors = collect_final_values(component)
    
            if not vals:
                ax.set_title(f"{title} (no data)", fontsize=16)
                ax.axis("off")
                continue
    
            x = np.arange(len(vals))
            ax.bar(x, vals, color=bar_colors, alpha=0.9)
            ax.set_yscale("log")
            ax.set_title(title, fontsize=16)
            ax.set_xlabel("")
            ax.set_ylabel("Final Loss", fontsize=14)
            ax.set_xticks(x)
            ax.set_xticklabels(xlabels, rotation=45, ha="right", fontsize=12)
            ax.grid(True, which="both", alpha=0.3)
            ax.legend(
                handles=legend_handles,
                title="Activation",
                loc="best",
                fontsize=10,
                title_fontsize=10,
            )
    
        # --------------------------------------------------
        # Layout first, then manually enlarge only [0,0]
        # --------------------------------------------------
        plt.tight_layout()
    
        # Slightly increase only subplot [0,0] height.
        # Keep the same width; move a bit downward and grow upward/downward.
        pos = ax_sol.get_position()
        ax_sol.set_position([
            pos.x0,            # same left
            pos.y0 - 0.038,    # slightly lower
            pos.width,         # same width
            pos.height + 0.042 # slightly taller
        ])
    
        save_path = os.path.join(
            save_dir,
            f"grid_search_comparison_bars_pair_{pair_idx + 1}.png",
        )
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
        plt.close(fig)
        print(f"Saved BAR layout to {save_path}")

    # ----------------------------- #
    # NEW: LINE plot layout (3x2)
    # ----------------------------- #
    def create_line_plot_layout(self, pair_idx, save_dir):
        """New 3x2 plot: same layout, but line plots vs epoch.
        Uses per-variant colors (same as subplot [2,1]).
        """
        variant_items = self._sorted_variant_items()

        fig, axes = plt.subplots(3, 2, figsize=(15, 13))
        # No figure title as requested
        
        # First row: [0,0] = Solution Comparison, [0,1] = Error History (swapped from bottom row)
        # Solution comparison at [0,0] (moved from [2,1])
        ax_sol = axes[0, 0]
        first_variant = list(self.variants.values())[0]
        d0 = first_variant["data"]
        M = d0["M"]
        Gamma = d0["Gamma"]
        chi = d0["chi"]

        ax_sol.plot(chi, h_analytical(chi, M), "k-", linewidth=2.5, label="Analytical", alpha=0.8)

        # Only plot Okwen point if within valid range
        if is_okwen_valid(M, Gamma):
            chi_max_okwen = compute_chi_max(M, Gamma)
            ax_sol.plot(
                chi_max_okwen, 1.0, "o",
                color="gray", markersize=8, markerfacecolor="gray",
                markeredgecolor="black", label="Okwen χ_max"
            )

        for _, info in variant_items:
            data = info["data"]
            style = info["style"]
            h_pinn = data.get("h_pinn", None)
            if h_pinn is None:
                continue
            ax_sol.plot(
                data["chi"],
                h_pinn,
                color=style.get("color", "black"),
                linestyle=style.get("linestyle", "-"),
                linewidth=2.0,
                alpha=0.85,
                label=style.get("label", "variant"),
            )

        ax_sol.set_xlabel("χ", fontsize=16)
        ax_sol.set_ylabel("h(χ)", fontsize=16)
        ax_sol.set_title(f"PINN Solution (M={M}, Γ={Gamma})", fontsize=18)
        ax_sol.grid(True, alpha=0.3)
        ax_sol.legend(loc="best", fontsize=10)
        ax_sol.set_ylim([-0.1, 1.1])

        # Error history at [0,1] (moved from [2,0])
        ax_err = axes[0, 1]
        plotted_any = False
        for _, info in variant_items:
            data = info["data"]
            style = info["style"]
            y = data.get("error_history", [])
            x = data.get("epochs", [])
            if y is None or len(y) == 0 or x is None or len(x) == 0:
                continue

            ax_err.plot(
                x, y,
                color=style.get("color", "black"),
                linestyle=style.get("linestyle", "-"),
                linewidth=2.0,
                alpha=0.85,
                label=style.get("label", "variant"),
            )
            plotted_any = True

        if not plotted_any:
            ax_err.set_title("Error History (no data)", fontsize=13)
            ax_err.axis("off")
        else:
            ax_err.set_yscale("log")
            ax_err.set_title("Error History (PINN vs Analytical)", fontsize=18)
            ax_err.set_xlabel("")
            ax_err.set_ylabel(r"$L_2(h_{\mathrm{PINN}}-h_{\mathrm{analytical}})$", fontsize=16)
            ax_err.grid(True, which="both", alpha=0.3)
            ax_err.legend(loc="best", fontsize=10, ncol=3)

        # Second and third rows: Loss components (shifted down)
        line_components = [
            ("ode_loss", "Residual Loss", axes[1, 0]),
            ("boundary_loss", "Boundary Loss", axes[1, 1]),
            ("integral_loss", "Integral Loss", axes[2, 0]),
            ("total_loss", "Total Loss", axes[2, 1]),
        ]

        # Loss histories (lines)
        for component, title, ax in line_components:
            plotted_any = False
            for _, info in variant_items:
                data = info["data"]
                style = info["style"]
                y = data.get(component, [])
                x = data.get("epochs", [])
                if y is None or len(y) == 0 or x is None or len(x) == 0:
                    continue

                ax.plot(
                    x, y,
                    color=style.get("color", "black"),
                    linestyle=style.get("linestyle", "-"),
                    linewidth=2.0,
                    alpha=0.85,
                    label=style.get("label", "variant"),
                )
                plotted_any = True

            if not plotted_any:
                ax.set_title(f"{title} (no data)", fontsize=13)
                ax.axis("off")
                continue

            ax.set_yscale("log")
            ax.set_title(title, fontsize=18)
            ax.set_xlabel("")
            ax.set_ylabel("Loss", fontsize=16)
            ax.grid(True, which="both", alpha=0.3)
            ax.legend(loc="best", fontsize=10, ncol=3)

        plt.tight_layout()
        save_path = os.path.join(save_dir, f"grid_search_comparison_lines_pair_{pair_idx + 1}.png")
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved LINE layout to {save_path}")

    def create_summary_table(self, save_dir):
        summary_data = []
        for _, info in self.variants.items():
            data = info["data"]
            if data and "total_loss" in data and len(data["total_loss"]) > 0:
                summary_data.append({
                    "Configuration": info["style"]["label"],
                    "Layers": info["layers"],
                    "Activation": info["activation"],
                    "Final ODE Loss": data["ode_loss"][-1] if data["ode_loss"] else float("nan"),
                    "Final Boundary Loss": data["boundary_loss"][-1] if data["boundary_loss"] else float("nan"),
                    "Final Integral Loss": data["integral_loss"][-1] if data["integral_loss"] else float("nan"),
                    "Final Total Loss": data["total_loss"][-1] if data["total_loss"] else float("nan"),
                    "Final Error": data["error_history"][-1] if data["error_history"] else float("nan"),
                    "Epochs": len(data["epochs"]),
                })

        if not summary_data:
            return None

        df = pd.DataFrame(summary_data).sort_values("Final Total Loss")
        csv_path = os.path.join(save_dir, "grid_search_summary.csv")
        df.to_csv(csv_path, index=False)

        print("Summary Table:")
        print(df.to_string(index=False, float_format="%.2e"))
        print(f"\nSaved summary table to {csv_path}")
        return df


def main():
    print("Base Case Grid Search Comparison Tool")
    print("=" * 70)

    comparator = LossComponentComparator()

    if not os.path.exists(comparator.grid_search_dir):
        print(f"Grid search directory not found: {comparator.grid_search_dir}")
        print("Please run the grid search first to generate results.")
        return

    # Clean and recreate output directory for fresh plots
    save_dir = "Validation_analytical_PINNs_base_case_grid_search_Loss_comparison"
    if os.path.exists(save_dir):
        shutil.rmtree(save_dir)
    os.makedirs(save_dir, exist_ok=True)
    print(f"Cleaned and recreated output directory: {save_dir}")

    # Only process Pair 1 since there's only one (M, Gamma) pair
    print(f"\nCreating comparison for Pair 1...")
    comparator.create_comparison_plots(pair_idx=0, save_dir=save_dir)

    print("\nGrid search comparison completed successfully!")


if __name__ == "__main__":
    main()
